//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima_ProductoComprado
    {
        public int idMateriaPrima_ProductoComprado { get; set; }
        public int cantidad { get; set; }
        public double precio { get; set; }
        public int idMateriaPrima { get; set; }
        public int idProductoComprado { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
        public virtual ProductoComprado ProductoComprado { get; set; }
    }
}
