//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MateriaPrima()
        {
            this.MateriaPrima_ProductoComprado = new HashSet<MateriaPrima_ProductoComprado>();
            this.MateriaPrima_ProductoPreEnsamblado = new HashSet<MateriaPrima_ProductoPreEnsamblado>();
        }
    
        public int idMateriaPrima { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public double precioCompra { get; set; }
        public double precioVenta { get; set; }
        public int cantidadStock { get; set; }
        public int idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriaPrima_ProductoComprado> MateriaPrima_ProductoComprado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriaPrima_ProductoPreEnsamblado> MateriaPrima_ProductoPreEnsamblado { get; set; }
    }
}
