//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoComprado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoComprado()
        {
            this.MateriaPrima_ProductoComprado = new HashSet<MateriaPrima_ProductoComprado>();
        }
    
        public int idProductoComprado { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public Nullable<System.DateTime> fechaEntregaPrevista { get; set; }
        public double costoEnsamblado { get; set; }
        public bool requiereEnsamblado { get; set; }
        public bool pedidoConfirmado { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriaPrima_ProductoComprado> MateriaPrima_ProductoComprado { get; set; }

        public static implicit operator ProductoComprado(List<ProductoComprado> v)
        {
            throw new NotImplementedException();
        }
    }
}
