//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPreEnsamblado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoPreEnsamblado()
        {
            this.MateriaPrima_ProductoPreEnsamblado = new HashSet<MateriaPrima_ProductoPreEnsamblado>();
        }
    
        public int idProductoPreEnsamblado { get; set; }
        public string descripcion { get; set; }
        public double costoEnsamblado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriaPrima_ProductoPreEnsamblado> MateriaPrima_ProductoPreEnsamblado { get; set; }
    }
}
